name: Setup Packit
description: Action that setups Packit cli and environment
inputs:
  python-version:
    description: Python version to use in actions/setup-python
    required: false
  packit-version:
    description: >
      Packit version to download via pip. Default is the latest version on PyPI
    required: false
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
      if: inputs.python-version
    - name: Install pre-requisites (Ubuntu)
      run: |
        if type -P apt; then
          sudo apt update
          sudo apt install python3-pycurl python3-gssapi python3-requests-kerberos python3-cccolutils python3-rpm
        elif type -P dnf; then
          sudo dnf install -y python3-pycurl python3-gssapi python3-requests-kerberos python3-cccolutils python3-rpm
        else
          echo "::error::Unsupported OS, use either Ubuntu or Fedora."
        fi
      shell: bash
    - name: Download Packit
      run: python3 -m pip install packitos${{ inputs.packit-version }}
      shell: bash
