name: CI
run-name: >
  CI (${{ github.event_name }})
  ${{ github.event_name == 'pull_request' && format('PR#{0}', github.event.number) || '' }}

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  setup-packit:
    uses: ./.github/workflows/step_test-setup-packit.yaml

  build-copr:
    needs: [setup-packit]
    uses: ./.github/workflows/step_test-build-copr.yaml

  pass:
    name: ✅ Pass
    needs: [setup-packit, build-copr]
    runs-on: ubuntu-latest
    steps:
      - name: Check all CI jobs
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
    if: always()
